services:
  - type: web
    name: inscripcio-voleibol
    env: python
    plan: free  # o 'starter' si vols més recursos
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false   # posa-ho després al panell de Render
      - key: SMTP_PASS
        sync: false   # posa-ho després al panell de Render
